[features]
seeds = false
skip-lint = false
[programs.localnet]
contract = "BiLy9N5Ngn3Yx37NZJof5YrdVXM7q7nn23SfmDt4cTUa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leqiang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
