[package]
name = "raydium_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-gen = "0.3.1"
anchor-lang = "0.28.0"
